best_layers_sentence = {'clip': {'languageLH': 'layer_13',
  'languageRH': 'layer_11',
  'visual': 'layer_2'},
 'align': {'languageLH': 'layer_4',
  'languageRH': 'layer_13',
  'visual': 'layer_4'},
 'lxmert': {'languageLH': 'layer_4',
  'languageRH': 'layer_14',
  'visual': 'layer_4'},
 'visualbert': {'languageLH': 'layer_1',
  'languageRH': 'layer_5',
  'visual': 'layer_1'},
 'llava': {'languageLH': 'layer_33',
  'languageRH': 'layer_4',
  'visual': 'layer_25'},
 'llama': {'languageLH': 'layer_20',
  'languageRH': 'layer_6',
  'visual': 'layer_23'},
 'idefics2': {'languageLH': 'layer_24',
  'languageRH': 'layer_33',
  'visual': 'layer_25'},
 'mistral': {'languageLH': 'layer_23',
  'languageRH': 'layer_33',
  'visual': 'layer_24'},
 'bert': {'languageLH': 'layer_2',
  'languageRH': 'layer_5',
  'visual': 'layer_4'}}

best_layers_picture = {'lxmert': {'languageLH': 'layer_14',
  'languageRH': 'layer_14',
  'visual': 'layer_14'},
 'visualbert': {'languageLH': 'layer_12',
  'languageRH': 'layer_1',
  'visual': 'layer_1'},
 'llava': {'languageLH': 'layer_31',
  'languageRH': 'layer_33',
  'visual': 'layer_31'},
 'llama': {'languageLH': 'layer_33',
  'languageRH': 'layer_33',
  'visual': 'layer_33'},
 'idefics2': {'languageLH': 'layer_27',
  'languageRH': 'layer_26',
  'visual': 'layer_27'},
 'mistral': {'languageLH': 'layer_33',
  'languageRH': 'layer_33',
  'visual': 'layer_33'},
 'bert': {'languageLH': 'layer_2',
  'languageRH': 'layer_2',
  'visual': 'layer_2'}}